### PR TITLE
Path for version 2019.R1

### PR DESCRIPTION
**Pull request by cabelo**
New path in version 2019.R1

### CODE REVIEW

**Comment by HernanG234** [comment]
Hi @cabelo! Thanks so much for your contributions :).
Did you have the chance to check if dependencies have changed? Did you try compiling and running against the new version of OpenVINO? If you have tested that and it still works we will merge it rightaway :D.

We're struggling a bit to find the time to check and update these changes, this would help us a lot.

**Comment by cabelo** [comment]
> Hi @cabelo! Thanks so much for your contributions :).
> Did you have the chance to check if dependencies have changed? Did you try compiling and running against the new version of OpenVINO? If you have tested that and it still works we will merge it rightaway :D.
> 
> We're struggling a bit to find the time to check and update these changes, this would help us a lot.
Hi @HernanG234 !

Everything is working now, I made some adjustments, compiled and tested.

**Comment by cabelo** [comment]
> > Hi @cabelo! Thanks so much for your contributions :).
> > Did you have the chance to check if dependencies have changed? Did you try compiling and running against the new version of OpenVINO? If you have tested that and it still works we will merge it rightaway :D.
> > We're struggling a bit to find the time to check and update these changes, this would help us a lot.
> > Hi @HernanG234 !
> 
> Everything is working now, I made some adjustments, compiled and tested.

@HernanG234 I already tested everything, it worked.

**Comment by cabelo** [comment]
> > Hi @cabelo! Thanks so much for your contributions :).
> > Did you have the chance to check if dependencies have changed? Did you try compiling and running against the new version of OpenVINO? If you have tested that and it still works we will merge it rightaway :D.
> > We're struggling a bit to find the time to check and update these changes, this would help us a lot.
> > Hi @HernanG234 !
> 
> Everything is working now, I made some adjustments, compiled and tested.

@HernanG234 I already tested everything, it worked.

**Comment by cabelo** [comment]
> > Hi @cabelo! Thanks so much for your contributions :).
> > Did you have the chance to check if dependencies have changed? Did you try compiling and running against the new version of OpenVINO? If you have tested that and it still works we will merge it rightaway :D.
> > We're struggling a bit to find the time to check and update these changes, this would help us a lot.
> > Hi @HernanG234 !
> 
> Everything is working now, I made some adjustments, compiled and tested.

**Comment by cabelo** [comment]
> > Hi @cabelo! Thanks so much for your contributions :).
> > Did you have the chance to check if dependencies have changed? Did you try compiling and running against the new version of OpenVINO? If you have tested that and it still works we will merge it rightaway :D.
> > We're struggling a bit to find the time to check and update these changes, this would help us a lot.
> > Hi @HernanG234 !
> 
> Everything is working now, I made some adjustments, compiled and tested.

**Comment by cabelo** [comment]
> > Hi @cabelo! Thanks so much for your contributions :).
> > Did you have the chance to check if dependencies have changed? Did you try compiling and running against the new version of OpenVINO? If you have tested that and it still works we will merge it rightaway :D.
> > We're struggling a bit to find the time to check and update these changes, this would help us a lot.
> > Hi @HernanG234 !
> 
> Everything is working now, I made some adjustments, compiled and tested.

**Pull request closed without merging**
