### PR TITLE
compatibility with OpenVINO 2019R1

### PR DESCRIPTION
**Pull request by cabelo**
Changed and tested the OpenVino-For-SmartCity project for the 2019 version R1

### CODE REVIEW

**Comment by cabelo** [comment]
@mauriff and @HernanG234  I tested all system. So this is my small contribution.

**Comment by HernanG234** [comment]
Hi @cabelo,

Sorry for the delayed response and thanks a lot for your contributions! I just wanted to check that no backwards compatibility was broken (that it still works for R4) but we're a bit overwhelmed right now. Anyway, don't worry, we didn't drop the project, we just need a bit of time. We'll be back to you soon!

**Comment by oititec** [comment]
> Hi @cabelo,
> 
> Sorry for the delayed response and thanks a lot for your contributions! I just wanted to check that no backwards compatibility was broken (that it still works for R4) but we're a bit overwhelmed right now. Anyway, don't worry, we didn't drop the project, we just need a bit of time. We'll be back to you soon!

Thank you, 
No problem, but if you do not remove the lines below the program does not compile in version 2019.
See below:
src/base_detection.hpp

**Comment by cabelo** [comment]
> Hi @cabelo,
> 
> Sorry for the delayed response and thanks a lot for your contributions! I just wanted to check that no backwards compatibility was broken (that it still works for R4) but we're a bit overwhelmed right now. Anyway, don't worry, we didn't drop the project, we just need a bit of time. We'll be back to you soon!

Thank you,
No problem, but if you do not remove the lines below the program does not compile in version 2019.
See below:

https://github.com/incluit/OpenVino-For-SmartCity/commit/51fd074cc7e4efa1fe912c27bbdc49e114ee2a81#diff-6a553804a10a376d191dec19f48b3b79

if possible, merge these changes, because I received some emails.

**Comment by HernanG234** [comment]
Hi @cabelo,

Thanks for your patience, but we won't merge the PR. It broke compilation for the 2018 R4 version but we already fixed it. (on this commit https://github.com/incluit/OpenVino-For-SmartCity/commit/73c3f7b6603f2a11cd8afb80be52055d11bcd20c).

We had to do a little hack to support R5 from R4 as `samples/ocv_common.hpp` didn't exist in R4. In `scripts/setupenv.sh` you can find that on the first lines. As the path changed from 2018 to 2019 we just added another if sentence.

Thanks again for your contributions!

**Pull request closed without merging**
